In [1]:
import duckdb, pandas as pd
pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)

con = duckdb.connect("new_data/energy.duckdb", read_only=True)

cal = con.execute("SELECT * FROM calendar ORDER BY timestamp_utc LIMIT 48").df()
print(cal.dtypes)
cal

timestamp_utc     datetime64[us, Europe/Copenhagen]
area                                            str
hour                                          int32
dow                                           int32
month                                         int32
doy                                           int32
is_weekend                                     bool
is_holiday                                     bool
holiday_name                                    str
hour_sin                                    float64
hour_cos                                    float64
doy_sin                                     float64
doy_cos                                     float64
dow_sin                                     float64
dow_cos                                     float64
daylight_hours                              float64
sunrise_hour                                float64
sunset_hour                                 float64
is_daylight                                    bool
dtype: object

,timestamp_utc,area,hour,dow,month,doy,is_weekend,is_holiday,holiday_name,hour_sin,hour_cos,doy_sin,doy_cos,dow_sin,dow_cos,daylight_hours,sunrise_hour,sunset_hour,is_daylight
0,2019-01-01 01:00:00+01:00,DK1,1,1,1,1,False,True,Nytårsdag,2.588190e-01,9.659258e-01,0.017213,0.999852,0.781831,0.623490,6.807283,8.596358,15.403642,False
1,2019-01-01 01:00:00+01:00,DK2,1,1,1,1,False,True,Nytårsdag,2.588190e-01,9.659258e-01,0.017213,0.999852,0.781831,0.623490,6.876231,8.561885,15.438115,False
2,2019-01-01 02:00:00+01:00,DK1,2,1,1,1,False,True,Nytårsdag,5.000000e-01,8.660254e-01,0.017213,0.999852,0.781831,0.623490,6.807283,8.596358,15.403642,False
3,2019-01-01 02:00:00+01:00,DK2,2,1,1,1,False,True,Nytårsdag,5.000000e-01,8.660254e-01,0.017213,0.999852,0.781831,0.623490,6.876231,8.561885,15.438115,False
4,2019-01-01 03:00:00+01:00,DK1,3,1,1,1,False,True,Nytårsdag,7.071068e-01,7.071068e-01,0.017213,0.999852,0.781831,0.623490,6.807283,8.596358,15.403642,False
5,2019-01-01 03:00:00+01:00,DK2,3,1,1,1,False,True,Nytårsdag,7.071068e-01,7.071068e-01,0.017213,0.999852,0.781831,0.623490,6.876231,8.561885,15.438115,False
6,2019-01-01 04:00:00+01:00,DK1,4,1,1,1,False,True,Nytårsdag,8.660254e-01,5.000000e-01,0.017213,0.999852,0.781831,0.623490,6.807283,8.596358,15.403642,False
7,2019-01-01 04:00:00+01:00,DK2,4,1,1,1,False,True,Nytårsdag,8.660254e-01,5.000000e-01,0.017213,0.999852,0.781831,0.623490,6.876231,8.561885,15.438115,False
8,2019-01-01 05:00:00+01:00,DK1,5,1,1,1,False,True,Nytårsdag,9.659258e-01,2.588190e-01,0.017213,0.999852,0.781831,0.623490,6.807283,8.596358,15.403642,False
9,2019-01-01 05:00:00+01:00,DK2,5,1,1,1,False,True,Nytårsdag,9.659258e-01,2.588190e-01,0.017213,0.999852,0.781831,0.623490,6.876231,8.561885,15.438115,False
10,2019-01-01 06:00:00+01:00,DK1,6,1,1,1,False,True,Nytårsdag,1.000000e+00,6.123234e-17,0.017213,0.999852,0.781831,0.623490,6.807283,8.596358,15.403642,False
11,2019-01-01 06:00:00+01:00,DK2,6,1,1,1,False,True,Nytårsdag,1.000000e+00,6.123234e-17,0.017213,0.999852,0.781831,0.623490,6.876231,8.561885,15.438115,False
12,2019-01-01 07:00:00+01:00,DK1,7,1,1,1,False,True,Nytårsdag,9.659258e-01,-2.588190e-01,0.017213,0.999852,0.781831,0.623490,6.807283,8.596358,15.403642,False
13,2019-01-01 07:00:00+01:00,DK2,7,1,1,1,False,True,Nytårsdag,9.659258e-01,-2.588190e-01,0.017213,0.999852,0.781831,0.623490,6.876231,8.561885,15.438115,False
14,2019-01-01 08:00:00+01:00,DK1,8,1,1,1,False,True,Nytårsdag,8.660254e-01,-5.000000e-01,0.017213,0.999852,0.781831,0.623490,6.807283,8.596358,15.403642,False
15,2019-01-01 08:00:00+01:00,DK2,8,1,1,1,False,True,Nytårsdag,8.660254e-01,-5.000000e-01,0.017213,0.999852,0.781831,0.623490,6.876231,8.561885,15.438115,False
16,2019-01-01 09:00:00+01:00,DK1,9,1,1,1,False,True,Nytårsdag,7.071068e-01,-7.071068e-01,0.017213,0.999852,0.781831,0.623490,6.807283,8.596358,15.403642,True
17,2019-01-01 09:00:00+01:00,DK2,9,1,1,1,False,True,Nytårsdag,7.071068e-01,-7.071068e-01,0.017213,0.999852,0.781831,0.623490,6.876231,8.561885,15.438115,True
18,2019-01-01 10:00:00+01:00,DK1,10,1,1,1,False,True,Nytårsdag,5.000000e-01,-8.660254e-01,0.017213,0.999852,0.781831,0.623490,6.807283,8.596358,15.403642,True
19,2019-01-01 10:00:00+01:00,DK2,10,1,1,1,False,True,Nytårsdag,5.000000e-01,-8.660254e-01,0.017213,0.999852,0.781831,0.623490,6.876231,8.561885,15.438115,True
20,2019-01-01 11:00:00+01:00,DK1,11,1,1,1,False,True,Nytårsdag,2.588190e-01,-9.659258e-01,0.017213,0.999852,0.781831,0.623490,6.807283,8.596358,15.403642,True
21,2019-01-01 11:00:00+01:00,DK2,11,1,1,1,False,True,Nytårsdag,2.588190e-01,-9.659258e-01,0.017213,0.999852,0.781831,0.623490,6.876231,8.561885,15.438115,True
22,2019-01-01 12:00:00+01:00,DK1,12,1,1,1,False,True,Nytårsdag,1.224647e-16,-1.000000e+00,0.017213,0.999852,0.781831,0.623490,6.807283,8.596358,15.403642,True
23,2019-01-01 12:00:00+01:00,DK2,12,1,1,1,False,True,Nytårsdag,1.224647e-16,-1.000000e+00,0.017213,0.999852,0.781831,0.623490,6.876231,8.561885,15.438115,True
24,2019-01-01 13:00:00+01:00,DK1,13,1,1,1,False,True,Nytårsdag,-2.588190e-01,-9.659258e-01,0.017213,0.999852,0.781831,0.623490,6.807283,8.596358,15.403642,True
25,2019-01-01 13:00:00+01:00,DK2,13,1,1,1,False,True,Nytårsdag,-2.588190e-01,-9.659258e-01,0.017213,0.999852,0.781831,0.623490,6.876231,8.561885,15.438115,True
26,2019-01-01 14:00:00+01:00,DK1,14,1,1,1,False,True,Nytårsdag,-5.000000e-01,-8.660254e-01,0.017213,0.999852,0.781831,0.623490,6.807283,8.596358,15.403642,True
27,2019-01-01 14:00:00+01:00,DK2,14,1,1,1,False,True,Nytårsdag,-5.000000e-01,-8.660254e-01,0.017213,0.999852,0.781831,0.623490,6.876231,8.561885,15.438115,True
28,2019-01-01 15:00:00+01:00,DK1,15,1,1,1,False,True,Nytårsdag,-7.071068e-01,-7.071068e-01,0.017213,0.999852,0.781831,0.623490,6.807283,8.596358,15.403642,True
29,2019-01-01 15:00:00+01:00,DK2,15,1,1,1,False,True,Nytårsdag,-7.071068e-01,-7.071068e-01,0.017213,0.999852,0.781831,0.623490,6.876231,8.561885,15.438115,True
30,2019-01-01 16:00:00+01:00,DK1,16,1,1,1,False,True,Nytårsdag,-8.660254e-01,-5.000000e-01,0.017213,0.999852,0.781831,0.623490,6.807283,8.596358,15.403642,False
31,2019-01-01 16:00:00+01:00,DK2,16,1,1,1,False,True,Nytårsdag,-8.660254e-01,-5.000000e-01,0.017213,0.999852,0.781831,0.623490,6.876231,8.561885,15.438115,False
32,2019-01-01 17:00:00+01:00,DK1,17,1,1,1,False,True,Nytårsdag,-9.659258e-01,-2.588190e-01,0.017213,0.999852,0.781831,0.623490,6.807283,8.596358,15.403642,False
33,2019-01-01 17:00:00+01:00,DK2,17,1,1,1,False,True,Nytårsdag,-9.659258e-01,-2.588190e-01,0.017213,0.999852,0.781831,0.623490,6.876231,8.561885,15.438115,False
34,2019-01-01 18:00:00+01:00,DK1,18,1,1,1,False,True,Nytårsdag,-1.000000e+00,-1.836970e-16,0.017213,0.999852,0.781831,0.623490,6.807283,8.596358,15.403642,False
35,2019-01-01 18:00:00+01:00,DK2,18,1,1,1,False,True,Nytårsdag,-1.000000e+00,-1.836970e-16,0.017213,0.999852,0.781831,0.623490,6.876231,8.561885,15.438115,False
36,2019-01-01 19:00:00+01:00,DK1,19,1,1,1,False,True,Nytårsdag,-9.659258e-01,2.588190e-01,0.017213,0.999852,0.781831,0.623490,6.807283,8.596358,15.403642,False
37,2019-01-01 19:00:00+01:00,DK2,19,1,1,1,False,True,Nytårsdag,-9.659258e-01,2.588190e-01,0.017213,0.999852,0.781831,0.623490,6.876231,8.561885,15.438115,False
38,2019-01-01 20:00:00+01:00,DK1,20,1,1,1,False,True,Nytårsdag,-8.660254e-01,5.000000e-01,0.017213,0.999852,0.781831,0.623490,6.807283,8.596358,15.403642,False
39,2019-01-01 20:00:00+01:00,DK2,20,1,1,1,False,True,Nytårsdag,-8.660254e-01,5.000000e-01,0.017213,0.999852,0.781831,0.623490,6.876231,8.561885,15.438115,False
40,2019-01-01 21:00:00+01:00,DK1,21,1,1,1,False,True,Nytårsdag,-7.071068e-01,7.071068e-01,0.017213,0.999852,0.781831,0.623490,6.807283,8.596358,15.403642,False
41,2019-01-01 21:00:00+01:00,DK2,21,1,1,1,False,True,Nytårsdag,-7.071068e-01,7.071068e-01,0.017213,0.999852,0.781831,0.623490,6.876231,8.561885,15.438115,False
42,2019-01-01 22:00:00+01:00,DK1,22,1,1,1,False,True,Nytårsdag,-5.000000e-01,8.660254e-01,0.017213,0.999852,0.781831,0.623490,6.807283,8.596358,15.403642,False
43,2019-01-01 22:00:00+01:00,DK2,22,1,1,1,False,True,Nytårsdag,-5.000000e-01,8.660254e-01,0.017213,0.999852,0.781831,0.623490,6.876231,8.561885,15.438115,False
44,2019-01-01 23:00:00+01:00,DK1,23,1,1,1,False,True,Nytårsdag,-2.588190e-01,9.659258e-01,0.017213,0.999852,0.781831,0.623490,6.807283,8.596358,15.403642,False
45,2019-01-01 23:00:00+01:00,DK2,23,1,1,1,False,True,Nytårsdag,-2.588190e-01,9.659258e-01,0.017213,0.999852,0.781831,0.623490,6.876231,8.561885,15.438115,False
46,2019-01-02 00:00:00+01:00,DK1,0,2,1,2,False,False,NaN,0.000000e+00,1.000000e+00,0.034422,0.999407,0.974928,-0.222521,6.832050,8.583975,15.416025,False
47,2019-01-02 00:00:00+01:00,DK2,0,2,1,2,False,False,NaN,0.000000e+00,1.000000e+00,0.034422,0.999407,0.974928,-0.222521,6.900545,8.549728,15.450272,False

In [8]:
con.execute("""
    SELECT
        timestamp_utc,
        strftime(timezone('Europe/Copenhagen', timestamp_utc), '%Y-%m-%d %H:%M %a') AS 丹麥當地,
        hour, dow, is_weekend, is_holiday, holiday_name,
        round(daylight_hours,1) AS 日照時數,
        round(sunrise_hour,2) AS 日出, round(sunset_hour,2) AS 日落,
        is_daylight AS 白天
    FROM calendar
    WHERE area='DK1'
    ORDER BY timestamp_utc
    LIMIT 48
    """).df()


df = con.execute("SELECT * FROM training WHERE area='DK1' ORDER BY timestamp_utc LIMIT 24").df()
print(len(df.columns), "欄:", list(df.columns))
df

39 欄: ['timestamp_utc', 'area', 'hour', 'dow', 'month', 'doy', 'is_weekend', 'is_holiday', 'holiday_name', 'hour_sin', 'hour_cos', 'doy_sin', 'doy_cos', 'dow_sin', 'dow_cos', 'daylight_hours', 'sunrise_hour', 'sunset_hour', 'is_daylight', 'wind_speed_100m', 'wind_gusts_10m', 'wind_direction_100m', 'shortwave_radiation', 'direct_radiation', 'diffuse_radiation', 'cloud_cover', 'temperature_2m', 'offshore_wind_da_mwh', 'onshore_wind_da_mwh', 'solar_da_mwh', 'load_mwh', 'wind_mwh', 'solar_mwh', 'residual_mwh', 'load_lag24_mwh', 'residual_lag24_mwh', 'price_lag24_eur', 'price_lag168_eur', 'y_price_eur']

,timestamp_utc,area,hour,dow,month,doy,is_weekend,is_holiday,holiday_name,hour_sin,hour_cos,doy_sin,doy_cos,dow_sin,dow_cos,daylight_hours,sunrise_hour,sunset_hour,is_daylight,wind_speed_100m,wind_gusts_10m,wind_direction_100m,shortwave_radiation,direct_radiation,diffuse_radiation,cloud_cover,temperature_2m,offshore_wind_da_mwh,onshore_wind_da_mwh,solar_da_mwh,load_mwh,wind_mwh,solar_mwh,residual_mwh,load_lag24_mwh,residual_lag24_mwh,price_lag24_eur,price_lag168_eur,y_price_eur
0,2019-01-01 01:00:00+01:00,DK1,1,1,1,1,False,True,Nytårsdag,2.588190e-01,9.659258e-01,0.017213,0.999852,0.781831,0.623490,6.807283,8.596358,15.403642,False,52.8,62.3,259,0.0,0.0,0.0,100,8.1,NaN,NaN,NaN,2182.800781,3122.389716,0.0,-939.588935,NaN,NaN,NaN,NaN,10.07
1,2019-01-01 02:00:00+01:00,DK1,2,1,1,1,False,True,Nytårsdag,5.000000e-01,8.660254e-01,0.017213,0.999852,0.781831,0.623490,6.807283,8.596358,15.403642,False,55.6,61.9,262,0.0,0.0,0.0,100,8.3,NaN,NaN,NaN,2164.288086,2621.214981,0.0,-456.926895,NaN,NaN,NaN,NaN,-4.08
2,2019-01-01 03:00:00+01:00,DK1,3,1,1,1,False,True,Nytårsdag,7.071068e-01,7.071068e-01,0.017213,0.999852,0.781831,0.623490,6.807283,8.596358,15.403642,False,55.8,63.4,269,0.0,0.0,0.0,100,8.7,NaN,NaN,NaN,2109.947998,2590.541888,0.0,-480.593890,NaN,NaN,NaN,NaN,-9.91
3,2019-01-01 04:00:00+01:00,DK1,4,1,1,1,False,True,Nytårsdag,8.660254e-01,5.000000e-01,0.017213,0.999852,0.781831,0.623490,6.807283,8.596358,15.403642,False,54.1,63.0,288,0.0,0.0,0.0,21,8.4,NaN,NaN,NaN,2083.668945,2519.920473,0.0,-436.251528,NaN,NaN,NaN,NaN,-7.41
4,2019-01-01 05:00:00+01:00,DK1,5,1,1,1,False,True,Nytårsdag,9.659258e-01,2.588190e-01,0.017213,0.999852,0.781831,0.623490,6.807283,8.596358,15.403642,False,56.8,62.3,284,0.0,0.0,0.0,26,6.8,NaN,NaN,NaN,2105.720947,2447.810169,0.0,-342.089222,NaN,NaN,NaN,NaN,-12.55
5,2019-01-01 06:00:00+01:00,DK1,6,1,1,1,False,True,Nytårsdag,1.000000e+00,6.123234e-17,0.017213,0.999852,0.781831,0.623490,6.807283,8.596358,15.403642,False,63.6,71.6,286,0.0,0.0,0.0,48,6.7,NaN,NaN,NaN,2119.425293,2673.759017,0.0,-554.333724,NaN,NaN,NaN,NaN,-17.25
6,2019-01-01 07:00:00+01:00,DK1,7,1,1,1,False,True,Nytårsdag,9.659258e-01,-2.588190e-01,0.017213,0.999852,0.781831,0.623490,6.807283,8.596358,15.403642,False,59.6,72.0,291,0.0,0.0,0.0,16,6.6,NaN,NaN,NaN,2208.502686,2691.168705,0.0,-482.666019,NaN,NaN,NaN,NaN,-15.07
7,2019-01-01 08:00:00+01:00,DK1,8,1,1,1,False,True,Nytårsdag,8.660254e-01,-5.000000e-01,0.017213,0.999852,0.781831,0.623490,6.807283,8.596358,15.403642,False,61.5,69.5,296,0.0,0.0,0.0,52,6.3,NaN,NaN,NaN,2289.313965,2616.056142,0.0,-326.742177,NaN,NaN,NaN,NaN,-4.93
8,2019-01-01 09:00:00+01:00,DK1,9,1,1,1,False,True,Nytårsdag,7.071068e-01,-7.071068e-01,0.017213,0.999852,0.781831,0.623490,6.807283,8.596358,15.403642,True,59.9,70.9,297,0.0,0.0,0.0,71,6.0,NaN,NaN,NaN,2342.314941,2879.190767,12.0,-548.875826,NaN,NaN,NaN,NaN,-6.33
9,2019-01-01 10:00:00+01:00,DK1,10,1,1,1,False,True,Nytårsdag,5.000000e-01,-8.660254e-01,0.017213,0.999852,0.781831,0.623490,6.807283,8.596358,15.403642,True,62.6,71.3,300,13.0,4.0,9.0,53,6.4,NaN,NaN,NaN,2454.776855,2790.205836,47.0,-382.428981,NaN,NaN,NaN,NaN,-4.93
10,2019-01-01 11:00:00+01:00,DK1,11,1,1,1,False,True,Nytårsdag,2.588190e-01,-9.659258e-01,0.017213,0.999852,0.781831,0.623490,6.807283,8.596358,15.403642,True,63.6,73.8,305,58.0,27.0,31.0,43,6.0,NaN,NaN,NaN,2484.070313,2882.988171,81.0,-479.917858,NaN,NaN,NaN,NaN,0.45
11,2019-01-01 12:00:00+01:00,DK1,12,1,1,1,False,True,Nytårsdag,1.224647e-16,-1.000000e+00,0.017213,0.999852,0.781831,0.623490,6.807283,8.596358,15.403642,True,63.4,74.2,306,97.0,51.0,46.0,48,5.6,NaN,NaN,NaN,2520.289307,2867.232004,96.0,-442.942697,NaN,NaN,NaN,NaN,0.12
12,2019-01-01 13:00:00+01:00,DK1,13,1,1,1,False,True,Nytårsdag,-2.588190e-01,-9.659258e-01,0.017213,0.999852,0.781831,0.623490,6.807283,8.596358,15.403642,True,62.8,92.2,304,108.0,55.0,53.0,30,5.0,NaN,NaN,NaN,2537.084229,2801.481201,78.0,-342.396972,NaN,NaN,NaN,NaN,-0.02
13,2019-01-01 14:00:00+01:00,DK1,14,1,1,1,False,True,Nytårsdag,-5.000000e-01,-8.660254e-01,0.017213,0.999852,0.781831,0.623490,6.807283,8.596358,15.403642,True,65.1,86.8,303,96.0,54.0,42.0,20,5.2,NaN,NaN,NaN,2515.121338,3012.718080,45.0,-542.596742,NaN,NaN,NaN,NaN,0.00
14,2019-01-01 15:00:00+01:00,DK1,15,1,1,1,False,True,Nytårsdag,-7.071068e-01,-7.071068e-01,0.017213,0.999852,0.781831,0.623490,6.807283,8.596358,15.403642,True,70.9,82.1,306,71.0,39.0,32.0,10,5.4,NaN,NaN,NaN,2431.857422,2906.077528,12.0,-486.220106,NaN,NaN,NaN,NaN,-0.03
15,2019-01-01 16:00:00+01:00,DK1,16,1,1,1,False,True,Nytårsdag,-8.660254e-01,-5.000000e-01,0.017213,0.999852,0.781831,0.623490,6.807283,8.596358,15.403642,False,72.6,83.5,316,19.0,9.0,10.0,8,5.0,NaN,NaN,NaN,2725.832275,3161.486814,1.0,-436.654539,NaN,NaN,NaN,NaN,1.97
16,2019-01-01 17:00:00+01:00,DK1,17,1,1,1,False,True,Nytårsdag,-9.659258e-01,-2.588190e-01,0.017213,0.999852,0.781831,0.623490,6.807283,8.596358,15.403642,False,70.0,83.9,316,0.0,0.0,0.0,36,4.4,NaN,NaN,NaN,2813.756592,3439.013368,0.0,-625.256776,NaN,NaN,NaN,NaN,9.06
17,2019-01-01 18:00:00+01:00,DK1,18,1,1,1,False,True,Nytårsdag,-1.000000e+00,-1.836970e-16,0.017213,0.999852,0.781831,0.623490,6.807283,8.596358,15.403642,False,61.9,79.9,322,0.0,0.0,0.0,12,4.3,NaN,NaN,NaN,2870.863281,3533.231169,0.0,-662.367888,NaN,NaN,NaN,NaN,0.07
18,2019-01-01 19:00:00+01:00,DK1,19,1,1,1,False,True,Nytårsdag,-9.659258e-01,2.588190e-01,0.017213,0.999852,0.781831,0.623490,6.807283,8.596358,15.403642,False,57.1,69.8,326,0.0,0.0,0.0,89,4.2,NaN,NaN,NaN,2782.317627,3071.580481,0.0,-289.262854,NaN,NaN,NaN,NaN,-4.97
19,2019-01-01 20:00:00+01:00,DK1,20,1,1,1,False,True,Nytårsdag,-8.660254e-01,5.000000e-01,0.017213,0.999852,0.781831,0.623490,6.807283,8.596358,15.403642,False,56.3,64.8,326,0.0,0.0,0.0,92,4.6,NaN,NaN,NaN,2662.238037,2998.532108,0.0,-336.294071,NaN,NaN,NaN,NaN,-6.98
20,2019-01-01 21:00:00+01:00,DK1,21,1,1,1,False,True,Nytårsdag,-7.071068e-01,7.071068e-01,0.017213,0.999852,0.781831,0.623490,6.807283,8.596358,15.403642,False,54.2,63.0,331,0.0,0.0,0.0,80,4.2,NaN,NaN,NaN,2475.885498,2809.660743,0.0,-333.775245,NaN,NaN,NaN,NaN,-16.01
21,2019-01-01 22:00:00+01:00,DK1,22,1,1,1,False,True,Nytårsdag,-5.000000e-01,8.660254e-01,0.017213,0.999852,0.781831,0.623490,6.807283,8.596358,15.403642,False,53.5,59.4,334,0.0,0.0,0.0,4,4.5,NaN,NaN,NaN,2401.986084,2612.735666,0.0,-210.749582,NaN,NaN,NaN,NaN,-4.87
22,2019-01-01 23:00:00+01:00,DK1,23,1,1,1,False,True,Nytårsdag,-2.588190e-01,9.659258e-01,0.017213,0.999852,0.781831,0.623490,6.807283,8.596358,15.403642,False,52.0,59.0,337,0.0,0.0,0.0,1,4.4,NaN,NaN,NaN,2205.978027,2477.606796,0.0,-271.628769,NaN,NaN,NaN,NaN,-28.93
23,2019-01-02 00:00:00+01:00,DK1,0,2,1,2,False,False,NaN,0.000000e+00,1.000000e+00,0.034422,0.999407,0.974928,-0.222521,6.832050,8.583975,15.416025,False,51.1,56.9,335,0.0,0.0,0.0,1,4.1,NaN,NaN,NaN,2108.695313,2311.696008,0.0,-203.000695,NaN,NaN,NaN,NaN,-33.57

In [ ]:
import pandas as pd
from entsoe import EntsoePandasClient
from entsoe.exceptions import NoMatchingDataError

# 把你的 key 放這；先故意留錯的或空的來測反應
API_KEY = "your-token-here"

client = EntsoePandasClient(api_key=API_KEY)

start = pd.Timestamp("20240101", tz="Europe/Copenhagen")
end   = pd.Timestamp("20240102", tz="Europe/Copenhagen")

try:
    prices = client.query_day_ahead_prices("DK_1", start=start, end=end)
    print("成功！拿到資料：")
    print(prices.head())
except Exception as e:
    print(f"錯誤類型：{type(e).__name__}")
    print(f"錯誤內容：{e}")

錯誤類型：HTTPError
錯誤內容：401 Client Error:  for url: https://web-api.tp.entsoe.eu/api?documentType=A44&in_Domain=10YDK-1--------W&out_Domain=10YDK-1--------W&offset=0&contract_MarketAgreement.type=A01&securityToken=your-token-here&periodStart=202312302300&periodEnd=202401022300

: